# Generated by Django 4.1.13 on 2024-03-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
    ]
